---
# follows the same parameter structure as the DB extractor configuration
cognite: # kwargs to pass to the CogniteClient, Environment variable format: ${ENVIRONMENT_VARIABLE}
    host: ${EXTPIPES_CDF_HOST}
    project: ${EXTPIPES_CDF_PROJECT}
    idp-authentication:
        client-id: ${EXTPIPES_IDP_CLIENT_ID}
        secret: ${EXTPIPES_IDP_CLIENT_SECRET}
        scopes:
            - ${EXTPIPES_IDP_SCOPES}
        token_url: ${EXTPIPES_IDP_TOKEN_URL}

logger:
    file:
        path: ./logs/extpipes-deploy.log
        level: INFO
    console:
        level: INFO

# extpipe-pattern only documentation atm
extpipe-pattern: '{source}:{short-name}:{rawtable-name}:{suffix}'

# can contain multiple contacts, can be overwritten on pipeline level
default-contacts:
    - name: Kiran
      email: kiran.sathaye@cognite.com
      role: Bootcamp 39 admin
      send-notification: false

rawdbs:
  # list of raw-dbs > containing rawtables > containing pipelines
    - rawdb-name: src:001:sap:db
      dataset-external-id: src:001:sap:ds
      short-name: sap
      rawtables:
          - rawtable-name: assets
            pipelines:
                - source: csv
                  schedule: On trigger
                  contacts:
                      - name: Kiran
                        email: kiran.sathaye@cognite.com
                        role: Bootcamp 39 admin
                        send-notification: false
    - rawdb-name: src:002:opcua:db
      short-name: opcua
      dataset-external-id: src:002:opcua:ds
      rawtables:
          - rawtable-name: raw_timeseries
            pipelines:
              - source: csv
                schedule: On trigger                
          - rawtable-name: datapoints
            pipelines:
                - source: ice-cream-api
                  schedule: On trigger


